# Generated by Django 3.1.5 on 2021-02-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderlineitem_c_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='c_date',
            new_name='date_choice',
        ),
    ]
