# Generated by Django 3.1.5 on 2021-02-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210205_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='book_type',
            field=models.CharField(choices=[('HD', 'Hardback'), ('KI', 'Kindle'), ('PB', 'Paperback')], default='PB', max_length=2),
        ),
    ]
