# Generated by Django 3.1.5 on 2021-02-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210205_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book_type',
            field=models.CharField(choices=[('Hardback', 'Hardback'), ('Kindle', 'Kindle'), ('Paperback', 'Paperback'), ('None', 'None')], default='None', max_length=254),
        ),
    ]
