# Generated by Django 3.1.5 on 2021-02-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210205_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book_type',
            field=models.CharField(choices=[('Hardback', 'Hardback'), ('Kindle', 'Kindle'), ('Paperback', 'Paperback'), ('None', '')], default='None', max_length=254),
        ),
    ]
