# Generated by Django 3.1.5 on 2021-02-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_remove_testimonial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='full_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
