# Generated by Django 3.1.5 on 2021-02-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210215_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
