# Generated by Django 3.1.5 on 2021-02-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='title',
        ),
    ]
