# Generated by Django 3.1.5 on 2021-02-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210220_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_available',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
