# Generated by Django 3.1.5 on 2021-02-21 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_date_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_available', models.CharField(blank=True, max_length=254, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available', related_query_name='available', to='products.product')),
            ],
        ),
    ]
