# Generated by Django 3.1.5 on 2021-02-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_datesavailable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_available',
            new_name='course_date',
        ),
    ]
