# Generated by Django 3.1.5 on 2021-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_a_video',
            field=models.BooleanField(default=False),
        ),
    ]
